name: Adjust notebook
on: [push]

jobs:
  add_badges:
    name: Add Google Colab badge to notebook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Add/Update badges
        uses: trsvchn/colab-badge-action@v4
        with:
          check: "all"
          target_branch: main
          target_repository: amateus1/dags_hub_final_project_2
          update: true
      
      - name: Add, commit, and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Action"
          author_email: "github-action@users.noreply.github.com"
          message: "Add Colab badge"
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.MLOPS }}

  black:
    name: Black Check for Jupyter notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black[jupyter]

      - name: Run Black
        run: black --exclude ./env/ .

      - name: Add, commit, and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Action"
          author_email: "github-action@users.noreply.github.com"
          message: "Reformat code with black"
          add: "."
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.MLOPS }}
